int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int omar_needs_this(int n, int s);
int is_prime_number(int n);
int omar_prime_fun(int n, int s);
int is_palindrome(char *s);
int omar_palindrome(char *s, int i);
